# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import health_export_pb2 as health__export__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in health_export_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class HealthExportServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SyncMetrics = channel.unary_unary(
                '/health_export.HealthExportService/SyncMetrics',
                request_serializer=health__export__pb2.SyncRequest.SerializeToString,
                response_deserializer=health__export__pb2.SyncResponse.FromString,
                _registered_method=True)
        self.GetCheckpoint = channel.unary_unary(
                '/health_export.HealthExportService/GetCheckpoint',
                request_serializer=health__export__pb2.CheckpointRequest.SerializeToString,
                response_deserializer=health__export__pb2.CheckpointResponse.FromString,
                _registered_method=True)
        self.SyncStream = channel.stream_stream(
                '/health_export.HealthExportService/SyncStream',
                request_serializer=health__export__pb2.SyncRequest.SerializeToString,
                response_deserializer=health__export__pb2.SyncResponse.FromString,
                _registered_method=True)
        self.Ping = channel.unary_unary(
                '/health_export.HealthExportService/Ping',
                request_serializer=health__export__pb2.PingRequest.SerializeToString,
                response_deserializer=health__export__pb2.PingResponse.FromString,
                _registered_method=True)


class HealthExportServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SyncMetrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCheckpoint(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SyncStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HealthExportServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SyncMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.SyncMetrics,
                    request_deserializer=health__export__pb2.SyncRequest.FromString,
                    response_serializer=health__export__pb2.SyncResponse.SerializeToString,
            ),
            'GetCheckpoint': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCheckpoint,
                    request_deserializer=health__export__pb2.CheckpointRequest.FromString,
                    response_serializer=health__export__pb2.CheckpointResponse.SerializeToString,
            ),
            'SyncStream': grpc.stream_stream_rpc_method_handler(
                    servicer.SyncStream,
                    request_deserializer=health__export__pb2.SyncRequest.FromString,
                    response_serializer=health__export__pb2.SyncResponse.SerializeToString,
            ),
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=health__export__pb2.PingRequest.FromString,
                    response_serializer=health__export__pb2.PingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'health_export.HealthExportService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('health_export.HealthExportService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HealthExportService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SyncMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/health_export.HealthExportService/SyncMetrics',
            health__export__pb2.SyncRequest.SerializeToString,
            health__export__pb2.SyncResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCheckpoint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/health_export.HealthExportService/GetCheckpoint',
            health__export__pb2.CheckpointRequest.SerializeToString,
            health__export__pb2.CheckpointResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SyncStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/health_export.HealthExportService/SyncStream',
            health__export__pb2.SyncRequest.SerializeToString,
            health__export__pb2.SyncResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/health_export.HealthExportService/Ping',
            health__export__pb2.PingRequest.SerializeToString,
            health__export__pb2.PingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
